INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Concordo plenamente, sou demasiado alto para o carro, mas vou dá-lo à minha filha.', 7, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('É verdade, também a uso e nunca tive problemas!', 1, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('É uma questão de hábito!', 12, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Aconteceu-me exatamente o mesmo...', 9, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Não devemos estar a falar da mesma madeira! Nem sequer faz chama...', 2, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Por acaso não concordo consigo, uso esta madeira há anos precisamente para cadeiras e mesas e nunca tive problemas.', 4, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Faço das minhas palavras as suas... muito mau.', 6, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Quando me apercebi que não era carro para mim já tinha desvalorizado uns milhares...', 12, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Verdade, bastou usar durante cerca de 1 mês para ter de deitar fora.', 11, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Eu até gostei! Acho um exagero este comentário.', 9, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Segui a sua review e não me arrependi. Vou começar a usar este ferro frequentemente.', 5, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('O padrão é demasiado irregular, eu particularmente não gosto muito... depende mesmo dos gostos', 3, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Verdade, parece que tem gasolina quando se deita lume!.', 2, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Sinceramente só me parece boa para queimar...', 1, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Esta madeira é melhor para outro tipo de aplicações.', 4, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Passado 1 ano as bicicletas ficam enferrujadas...', 5, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Por acaso até gosto mais destas do que das bananas da Madeira!', 8, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Isso é muito subjetivo! São as minhas bolachas preferidas!', 6, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Serve perfeitamente, apesar de não ser a mais indicada.', 4, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('É um carro indicado para pessoas pequenas em geral, não necessariamente mulheres!', 7, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Verdade, das favoritas dos meus clientes(sou dono de uma fábrica de móveis).', 3, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Concordo a 100%, das melhores que comi a nível de qualidade/preço!', 8, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Espere mais uns meses e vai ver se não oxida!', 10, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Para já não tenho queixas, não tem um pingo de oxidação.', 10, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Isso é por culpa do fogão! A minha está impecável.', 11, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Isso é por culpa do fogão! A minha está impecável.', 1, false);

