@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Customer" as User
participant ":ProductController" as Ctrl
participant "productService:ProductService" as Service
participant "productRepository:ProductRepository" as Repo

activate User

User -> Ctrl: types product designation or sku

Ctrl -> Service: getProductsByProductName(final String name)
Service -> Repo: findByProductName(final String name)
Repo --> Repo: findByProductName(String designation)
Repo --> Service: product
Service --> Ctrl: product
Ctrl --> User: shows the product

@enduml