@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Registered Customer" as User
participant ":System" as System

activate User

User -> System: requests aggregated rating of a product
User <-- System: shows products aggregated rating

@enduml
