@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Registered Costumer" as User
participant "System" as System

activate User

User -> System: User asks to vote for a review
User <-- System: System acknowledges and adds a vote to the review

@enduml