@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "User" as user
participant ":System" as System

activate user

user -> System: asks to list their reviews
System --> user: requests reviewId
user -> System: types reviewId
System --> user: shows review
user -> System: types changes
System --> user: shows updated review

@enduml