@startuml
 'https://plantuml.com/class-diagram

 hide circle
 skinparam classAttributeIconSize 0


 class UserBootstrapper {
    +CommandLineRunner
 }



 class User {
     - userId
     - username
     - password
     - roleId
     User(Long userId, String username, String password,Long roleId)
 }



 UserBootstrapper "1" --> "0.." User:  creates






 @enduml