@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Registered Customer" as User
participant ":ReviewController" as Ctrl
participant "service:VoteService" as Service2
participant "service:ReviewService" as Service
participant "repo:VoteRepository" as Repo2
participant "repo:ReviewRepository" as Repo
participant "Review" as Review


activate User

User -> Ctrl: asks to delete a review
Ctrl -> Service2: getVotesByReviewId(reviewId)
Service2 -> Repo2: getVotesByReviewId(reviewId)
Repo2 --> Ctrl: number of votes
alt if no votes
Ctrl -> Service: withdrawReview()
Service -> Repo: deleteById(reviewId)
Repo --> Repo: deleteByIdIfMatch()
else if there's votes
Service --> Ctrl: ResponseStatusException()
Ctrl --> User: Informs operation invalid
end alt

@enduml