@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
hide circle
hide methods

class ACME {
}

class Review {
     - reviewId
     - sku
     - userId
     - rating
     - text
     - publishingDate
     - funfact
     - statusId
}

ACME "1" -right-- "0..*" Review:  lists >


@enduml