@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Moderator" as Mod
participant ":System" as System

activate Mod

Mod -> System: asks to list pending reviews
System --> Mod: shows all pending reviews

@enduml