@startuml
'https://plantuml.com/class-diagram

hide circle
hide methods
left to right direction


class Product {
    - productId
    - designation
    - description
    - setOfImg
    - sku
    - aggregatedRating
}

class Review {
     - reviewId
     - sku
     - userId
     - rating
     - text
     - publishingDate
     - funfact
     - statusId
}

class User {
    - userId
    - roleId
    - username
    - password
}

User "1" -down-- "1" Review: reviews
Review "1" -right-- "1" Product: has

@enduml
