@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Customer" as User
participant ":ProductController" as Ctrl
participant "productService:ProductService" as Service
participant "productRepository:ProductRepository" as Repo

activate User

User -> Ctrl: asks to show the details of a product
Ctrl -> Service: findBySku(String sku)
Service -> Repo: findBySku(String sku)
Repo --> Service: details
Service --> Ctrl: details

Ctrl --> User: shows the details of the selected product

@enduml