INSERT INTO REVIEW (user_Id, sku, rating, text, publishing_Date, fun_Fact, status) VALUES (4,'SKU0000001',5,'Madeira de muita qualidade, fantástica para fabrico de móveis. Recomendo', '1999-06-22', 'June 22nd is the day in 1942 that Erwin Rommel is promoted to Field Marshal after the capture of Tobruk.', 1);
INSERT INTO REVIEW (user_Id, sku, rating, text, publishing_Date, fun_Fact, status) VALUES (5,'SKU0000001',5,'Madeira muito boa para usar como lenha.', '1998-08-09', 'August 9th is the day in 1965 that Singapore is expelled from Malaysia and becomes the first and only country to date to gain independence unwillingly.', 1);
INSERT INTO REVIEW (user_Id, sku, rating, text, publishing_Date, fun_Fact, status) VALUES (6,'SKU0000001',4,'Muito boa madeira para mesas, fica lindíssima, apenas necessita do verniz adequado.','2001-10-22', 'October 22nd is the day in 1927 that Nikola Tesla exposed his six (6) new inventions including motor with onephase electricity.', 1);
INSERT INTO REVIEW (user_Id, sku, rating, text, publishing_Date, fun_Fact, status) VALUES (11,'SKU0000001',1,'Madeira péssima para fabricar cadeiras, apodrece muito rapidamente!', '2004-04-29', 'April 29th is the day in 1953 that the first U.S. experimental 3D-TV broadcast showed an episode of Space Patrol on Los Angeles ABC affiliate KECA-TV.', 0);
INSERT INTO REVIEW (user_Id, sku, rating, text, publishing_Date, fun_Fact, status) VALUES (9,'SKU0000002',4,'Ótimo ferro para fabricar quadros de bicicletas.', '2000-02-13', 'February 13th is the day in 1542 that Catherine Howard, the fifth wife of Henry VIII of England, is executed for adultery.', 0);
INSERT INTO REVIEW (user_Id, sku, rating, text, publishing_Date, fun_Fact, status) VALUES (4,'SKU0000003',1,'Sabor péssimo, sem palavras!', '1999-05-01', 'May 1st is the day in 1894 that Coxey´s Army, the first significant American protest march, arrives in Washington, D.C.', 1);
INSERT INTO REVIEW (user_Id, sku, rating, text, publishing_Date, fun_Fact, status) VALUES (6,'SKU0000006',5,'Melhor carro para mulheres, a não ser que sejam altas!', '2018-08-09', 'August 9th is the day in 1854 that Henry David Thoreau published Walden.', 0);
INSERT INTO REVIEW (user_Id, sku, rating, text, publishing_Date, fun_Fact, status) VALUES (8,'SKU0000005',3,'Banana muito boa, mas as da Madeira são melhores!', '2000-02-13', 'February 13th is the day in 1689 that William and Mary are proclaimed co-rulers of England.', 0);
INSERT INTO REVIEW (user_Id, sku, rating, text, publishing_Date, fun_Fact, status) VALUES (7,'SKU0000005',1,'Tive de deitar ao lixo apesar de ser totalmente contra desperdiçar comida, impossível alguém conseguir comer isto!', '2006-12-14', 'December 14th is the day in 1782 that the Montgolfier brothers´ first balloon lifts off on its first test flight.', 0);
INSERT INTO REVIEW (user_Id, sku, rating, text, publishing_Date, fun_Fact, status) VALUES (5,'SKU0000002',5,'Ferro de muita qualidade, não oxida facilmente!', '2009-09-30', 'September 30th is the day in 1994 that Aldwych tube station (originally Strand Station) of the London Underground closes after eighty-eight years of service.', 0);
INSERT INTO REVIEW (user_Id, sku, rating, text, publishing_Date, fun_Fact, status) VALUES (12,'SKU0000004',1,'Panela rapidamente queimou e tive de deitar ao lixo. Vergonhoso', '2011-07-20', 'July 20th is the day in 1960 that Ceylon (now Sri Lanka) elects Sirimavo Bandaranaike Prime Minister, the world´s first elected female head of government.', 0);
INSERT INTO REVIEW (user_Id, sku, rating, text, publishing_Date, fun_Fact, status) VALUES (10,'SKU0000006',2,'Arrependi-me de comprar o carro pois sou demasiado alto para o conduzir. Vou dar à minha filha, é o carro indicado para ela.', '2019-05-12', 'May 12th is the day in 1870 that the Manitoba Act is given the Royal Assent, paving the way for Manitoba to become a province of Canada on July 15.', 0);
INSERT INTO REVIEW (user_Id, sku, rating, text, publishing_Date, fun_Fact, status) VALUES (10,'SKU0000003',2,'Arrependi-me de comprar o carro pois sou demasiado alto para o conduzir. Vou dar à minha filha, é o carro indicado para ela.', '2019-05-12', 'May 12th is the day in 1870 that the Manitoba Act is given the Royal Assent, paving the way for Manitoba to become a province of Canada on July 15.', 1);


DELETE PRODUCT WHERE Designation='madeira';
INSERT INTO PRODUCT (designation, description, sku) VALUES ('madeira','A madeira é um material produzido a partir do tecido formado pelas plantas lenhosas com funções de sustentação mecânica.', 'SKU0000001');
DELETE PRODUCT WHERE Designation='ferro';
INSERT INTO PRODUCT (designation, description, sku) VALUES ('ferro','O ferro (do latim ferrum) é um elemento químico, símbolo Fe, de número atômico 26 (26 prótons e 26 elétrons) e massa atômica 56 u.', 'SKU0000002');
DELETE PRODUCT WHERE Designation='bolacha';
INSERT INTO PRODUCT (designation, description, sku) VALUES ('bolacha','A bolacha é um bolo chato e seco de farinha de diversas formas e tamanhos. Pode ser consumida de diversas maneiras, doce, com recheios, salgada ou acompanhada de especiarias e/ou patês', 'SKU0000003');
DELETE PRODUCT WHERE Designation='panela';
INSERT INTO PRODUCT (designation, description, sku) VALUES ('panela','As panelas são uma família de utensílios culinários consideradas por muitos como indispensáveis em qualquer cozinha. São geralmente de forma cilíndrica ou subesférica e normalmente têm uma tampa e uma ou duas pegas (cabos).', 'SKU0000004');
DELETE PRODUCT WHERE Designation='banana';
INSERT INTO PRODUCT (designation, description, sku) VALUES ('banana','A banana é uma pseudobaga da bananeira, uma planta herbácea vivaz acaule da família Musaceae . São cultivadas em 130 países. Originárias do sudeste da Ásia são atualmente cultivadas em praticamente todas as regiões tropicais do planeta', 'SKU0000005');
DELETE PRODUCT WHERE Designation='fiat 500';
INSERT INTO PRODUCT (designation, description, sku) VALUES ('fiat 500','O fiat 500 (Cinquecento) foi um modelo de minicarro produzido pela Fiat na Italia, entre 1957 e 1975. Criado por Dante Giacosa, o carro utiliza a sigla ZFA 110 para a versão sedã e ZFA 120 para a versão Giardiniera.', 'SKU0000006');


INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Verdade, parece que tem gasolina quando se deita lume!.', 2, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Sinceramente só me parece boa para queimar...', 1, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Esta madeira é melhor para outro tipo de aplicações.', 4, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Passado 1 ano as bicicletas ficam enferrujadas...', 5, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Por acaso até gosto mais destas do que das bananas da Madeira!', 8, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Isso é muito subjetivo! São as minhas bolachas preferidas!', 6, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Serve perfeitamente, apesar de não ser a mais indicada.', 4, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('É um carro indicado para pessoas pequenas em geral, não necessariamente mulheres!', 7, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Verdade, das favoritas dos meus clientes(sou dono de uma fábrica de móveis).', 3, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Concordo a 100%, das melhores que comi a nível de qualidade/preço!', 8, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Espere mais uns meses e vai ver se não oxida!', 10, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Para já não tenho queixas, não tem um pingo de oxidação.', 10, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Isso é por culpa do fogão! A minha está impecável.', 11, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Isso é por culpa do fogão! A minha está impecável.', 1, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Concordo plenamente, sou demasiado alto para o carro, mas vou dá-lo à minha filha.', 7, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('É verdade, também a uso e nunca tive problemas!', 1, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('É uma questão de hábito!', 12, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Aconteceu-me exatamente o mesmo...', 9, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Não devemos estar a falar da mesma madeira! Nem sequer faz chama...', 2, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Por acaso não concordo consigo, uso esta madeira há anos precisamente para cadeiras e mesas e nunca tive problemas.', 4, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Faço das minhas palavras as suas... muito mau.', 6, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Quando me apercebi que não era carro para mim já tinha desvalorizado uns milhares...', 12, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Verdade, bastou usar durante cerca de 1 mês para ter de deitar fora.', 11, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Eu até gostei! Acho um exagero este comentário.', 9, false);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('Segui a sua review e não me arrependi. Vou começar a usar este ferro frequentemente.', 5, true);
INSERT INTO VOTE (reason, review_Id, vote) VALUES ('O padrão é demasiado irregular, eu particularmente não gosto muito... depende mesmo dos gostos', 3, false);