@startuml
'https://plantuml.com/class-diagram

hide circle
hide methods
left to right direction


class Product {
    - productId
    - designation
    - description
    - setOfImg
    - sku
    - aggregatedRating
}

class Review {
     - reviewId
     - sku
     - userId
     - rating
     - text
     - publishingDate
     - funFact
     - status
}

class Vote {
    - reviewId
    - userId
    - voteId
    - vote
    - reason
}

Review "1" -right-- "1" Product: has
Review "1" -down-- "0..*" Vote: has

@enduml
