@startuml
'https://plantuml.com/sequence-diagram

autoactivate on
autonumber

actor "Registered Customer" as User
participant ":ReviewController" as Ctrl
participant "reviewService:ReviewService" as Service
participant "reviewRepository:ReviewRepository" as Repo


activate User

User -> Ctrl: asks to list reviews of a product
Ctrl -> Service: findReviewsBySkuSortedByVotesAndDate()
Service -> Repo: findReviewsBySkuSortedByVotesAndDate()
Repo --> Repo: findReviewsBySkuSortedByVotesAndDate()
Repo --> Service: Reviews List
Service --> Ctrl: Reviews List
Ctrl --> User: shows the reviews list of the selected product


@enduml