@startuml
'https://plantuml.com/sequence-diagram

hide circle
hide methods
left to right direction

class Product {
    - designation
}

class User {
    - userId
    - roleId
    - username
    - password
}

class Role {
    - roleId
    - designation
}

User "1" --- "1..*" Role: has a
Role "1" -down-- "1" Product: is admin and boostraps




@enduml